version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      # --@STCGoal Automate stuff when you publish an element of your research.
      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date